version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: videos
    volumes:
      - postgres-data:/var/lib/posgresql/data

volumes:
  postgres-data: